nav:
  - index.md
  - table-management-grid-label-text.md
  - table-management-grid-format.md
  - table-management-extended-cell-css.md
  - table-management-grid-sticky-on-left-edge.md
  - table-management-grid-cell-width.md
  - table-management-grid-wordwrap.md
  - table-management-use-grid-design.md
