title: サイト機能

nav:
  - index.md
  - site-custom-apps-new.md
  - site-delete.md
  - site-new.md
  - site-sort.md
  - site-move.md
  - site-copy.md
  - site-delete-from-trash.md
  - site-restore.md
  - site-edit.md
  - site-guide.md
  - site-simplemode.md
  - site-image.md
  - site-information.md
  - site-breadcrumb-list.md
