nav:
  - index.md
  - table-management-filter-num-filter-mode.md
  - table-management-filter-num-filter-mim-and-max.md
  - table-management-filter-date-filter-mode.md
  - table-management-filter-date-filter-mim-and-max.md
  - table-management-filter-check-filter-control-type.md
  - table-management-filter-search-types.md
