title: FAQ

nav:
  - index.md
  - login
  - top-screen-site-menu
  - editor
  - grid
  - system-administration-operations-and-settings
  - others
  - system-requirements-and-setup
  - backup-restore
  - features-for-developers
  - operations-and-maintenance
  - license
  - pleasanter.net
  - sample-codes
