title: Windowsの機能の有効化

nav:
  - index.md
  - feature-activation-windows-server2025.md
  - feature-activation-windows-server2022.md
  - feature-activation-windows-server2019.md
  - feature-activation-windows-server2016.md
  - feature-activation-windows10.md
