title: 応用編

nav:
  - index.md
  - advanced-operations-column.md
  - advanced-operations-grid.md
  - advanced-operations-link.md
  - advanced-operations-copy.md
  - advanced-operations-notification.md
  - advanced-operations-view.md
  - advanced-operations-process.md
  - advanced-operations-extended.md
  - advanced-operations-authentication.md
  - shortcut.md
  - advanced-operations-task.md
