title: プリザンターのインストール

nav:
  - index.md
  - getting-preparation-pleasanter-windows.md
  - getting-started-pleasanter-windows.md
  - getting-started-pleasanter-windows-server2025.md
  - getting-started-pleasanter-windows-server2022.md
  - getting-started-pleasanter-windows-server2019.md
  - getting-started-pleasanter-windows-server2016.md
  - getting-started-pleasanter-windows10.md
  - getting-started-pleasanter-azure.md
  - getting-started-pleasanter-azure-mysql.md
  - getting-started-pleasanter-rhel10-aws.md
  - getting-started-pleasanter-ubuntu.md
  - getting-started-pleasanter-almalinux.md
  - getting-started-pleasanter-rhel.md
  - getting-started-pleasanter-rhel-8.md
