nav:
  - index.md
  - 全般: general
  - ガイド: guide
  - サイト画像: site-image
  - 一覧: grid
  - フィルタ: filter
  - 集計: aggregations
  - エディタ: editor
  - フォーム: form
  - リンク: links
  - 履歴: history
  - 移動: move
  - サマリ: summaries
  - 計算式: formulas
  - AI連携: ai-connect
  - プロセス: process
  - 状況による制御: control-by-status
  - ビュー: view
  - 通知: notifications
  - リマインダー: reminders
  - インポート: import
  - エクスポート: export
  - カレンダー: calendar
  - クロス集計: crosstab
  - ガントチャート: gantt-chart
  - バーンダウンチャート: burndown-chart
  - 時系列チャート: time-series-chart
  - 分析チャート: analysis-chart
  - カンバン: kanban
  - 画像ライブラリ: image-library
  - 検索: search
  - メール: email
  - サイト統合: site-integration
  - スタイル: styles
  - スクリプト: scripts
  - HTML: html
  - サーバスクリプト: server-script
  - 公開: publish
  - サイトのアクセス制御: site-access-control
  - レコードのアクセス制御: record-access-control
  - 項目のアクセス制御: column-access-control
  - 共通機能: common
  - サイトパッケージ: site-package
