title: 値の操作

nav:
  - index.md
  - script-id.md
  - script-site-id.md
  - script-login-id.md
  - script-user-id.md
  - script-user-name.md
  - script-get-column-name.md
  - script-get-control.md
  - script-get-field.md
  - script-get-grid-row.md
  - script-get-grid-cell.md
  - script-get-column-index.md
  - script-on.md
