nav:
  - index.md
  - table-management-label-text.md
  - table-management-textalign.md
  - table-management-maxlength.md
  - table-management-field-css.md
  - table-management-change-viewer.md
  - table-management-required.md
  - table-management-editor-format.md
  - table-management-date-time-step.md
  - table-management-bulk-update.md
  - table-management-no-duplication.md
  - table-management-no-duplication-message.md
  - table-management-copy-by-default.md
  - table-management-import-key.md
  - table-management-input-guide.md
  - table-management-readonly.md
  - table-management-default-input.md
  - table-management-format.md
  - table-management-nullable.md
  - table-management-anchor.md
  - table-management-unit.md
  - table-management-decimal-places.md
  - table-management-rounding-type.md
  - table-management-control-type-class.md
  - table-management-control-type.md
  - table-management-min-and-max.md
  - table-management-binary-storage-provider.md
  - table-management-allow-delete-attachments.md
  - table-management-overwrite-same-file-name.md
  - table-management-not-delete-file-with-history.md
  - table-management-limit-quantity.md
  - table-management-limit-size.md
  - table-management-limit-total-size.md
  - table-management-local-folder-limit-size.md
  - table-management-local-folder-limit-total-size.md
  - 選択肢一覧: option-list
  - table-management-use-search.md
  - table-management-multiple-selections.md
  - table-management-not-insert-blank-choice.md
  - table-management-auto-postback.md
  - table-management-columns-returned-when-automatic-postback.md
  - table-management-no-wrap.md
  - table-management-hide.md
  - table-management-extended-field-css.md
  - table-management-extended-control-css.md
  - table-management-full-text-type.md
  - table-management-allow-adding-img.md
  - table-management-thumbnail.md
  - table-management-title-combination.md
  - table-management-column-description.md
  - table-management-record-lock.md
  - table-management-section.md
