title: プリザンターのインストール（インストーラ）

nav:
  - index.md
  - getting-started-installer-pleasanter-windows.md
  - getting-started-installer-pleasanter-azure.md
  - getting-started-installer-pleasanter-rhel10-aws.md
  - getting-started-installer-pleasanter-ubuntu.md
  - getting-started-installer-pleasanter-almalinux.md
  - getting-started-installer-pleasanter-rhel9.md
  - getting-started-installer-pleasanter-rhel-8.md
